"""Storeye business/data models (PostgreSQL-backed).

Importing this package registers all models on the SQLAlchemy Base
metadata so Alembic can autogenerate migrations, and `create_all` can
build the full schema.
"""

from .store import Store
from .user import User
from .auth_session import AuthSession
from .camera import Camera
from .zone import Zone
from .shelf import Shelf
from .product import Product
from .inventory import Inventory
from .inventory_movement import InventoryMovement
from .batch import Batch, BATCH_PRECISION_DAY, BATCH_PRECISION_MONTH
from .planogram import Planogram, PlanogramItem
from .customer import Customer
from .sale import Sale, SaleItem
from .bill import Bill, BillItem
from .sms_message import (
    SmsMessage,
    MSG_QUEUED,
    MSG_SENDING,
    MSG_SENT,
    MSG_FAILED,
    VALID_MESSAGE_STATUSES,
    DEFAULT_SMS_PROVIDER,
)
from .notification import Notification
from .alert import (
    Alert,
    ALERT_SHORTAGE,
    ALERT_SURPLUS,
    ALERT_MISPLACEMENT,
    ALERT_EXPIRY,
    ALERT_LOW_SHELF_OCCUPANCY,
    ALERT_SHELF_EMPTY,
    ALERT_CAMERA_OFFLINE,
    ALERT_REVIEW_REQUIRED,
    VALID_ALERT_TYPES,
    SEV_INFO,
    SEV_LOW,
    SEV_MEDIUM,
    SEV_HIGH,
    SEV_CRITICAL,
    VALID_SEVERITIES,
    STATUS_OPEN,
    STATUS_ACKNOWLEDGED,
    STATUS_RESOLVED,
    STATUS_DISMISSED,
    VALID_STATUSES,
    ALLOWED_TRANSITIONS,
)
from .observation import (
    Observation,
    OBS_PERSON,
    OBS_PRODUCT,
    OBS_TEXT,
    OBS_EXPIRY_METADATA,
    VALID_OBSERVATION_TYPES,
)
from .shelf_snapshot import (
    ShelfSnapshot,
    SNAPSHOT_EMPTY,
    SNAPSHOT_LOW,
    SNAPSHOT_MEDIUM,
    SNAPSHOT_FULL,
    VALID_SNAPSHOT_STATUSES,
)
from .reconciliation_result import (
    ReconciliationResult,
    REC_MATCH,
    REC_SURPLUS,
    REC_SHORTAGE,
    REC_REVIEW,
    VALID_RECONCILIATION_STATUSES,
)
from .journeys import (
    GlobalPersonSession,
    PersonTrackAssociation,
    ZoneVisit,
    PersonCameraTransition,
    CONF_HIGH,
    CONF_MEDIUM,
    CONF_LOW,
    CONF_UNKNOWN,
    VALID_CONFIDENCES,
    SESSION_ACTIVE,
    SESSION_EXPIRED,
)
from .demo import DemoScenarioState
from .insight import (
    Insight,
    CATEGORY_INVENTORY,
    CATEGORY_SHELF,
    CATEGORY_EXPIRY,
    CATEGORY_CUSTOMER_FLOW,
    CATEGORY_CAMERA,
    CATEGORY_STORE_HEALTH,
    VALID_CATEGORIES,
    INSIGHT_LOW_STOCK,
    INSIGHT_OUT_OF_STOCK,
    INSIGHT_LOW_STOCK_LOW_SHELF,
    INSIGHT_HIGH_SELLING_LOW_STOCK,
    INSIGHT_EXPIRY_RISK,
    INSIGHT_EXPIRED_BATCH,
    INSIGHT_STOCK_ROTATION,
    INSIGHT_LOW_SHELF_AVAILABILITY,
    INSIGHT_MISPLACEMENT,
    INSIGHT_HIGH_TRAFFIC_ZONE,
    INSIGHT_HIGH_DWELL_ZONE,
    INSIGHT_HIGH_TRAFFIC_LOW_SHELF,
    INSIGHT_CAMERA_HEALTH,
    INSIGHT_INVENTORY_RISK,
    INSIGHT_STORE_HEALTH,
    VALID_INSIGHT_TYPES,
    VALID_SEVERITIES,
    STATUS_OPEN,
    STATUS_ACKNOWLEDGED,
    STATUS_RESOLVED,
    STATUS_EXPIRED,
    VALID_STATUSES,
    CERTAINTY_HIGH,
    CERTAINTY_MEDIUM,
    CERTAINTY_LOW,
    VALID_CERTAINTIES,
)

__all__ = [
    "Store",
    "DemoScenarioState",
    "User",
    "AuthSession",
    "Camera",
    "Zone",
    "Shelf",
    "Product",
    "Inventory",
    "InventoryMovement",
    "Batch",
    "BATCH_PRECISION_DAY",
    "BATCH_PRECISION_MONTH",
    "Planogram",
    "PlanogramItem",
    "Customer",
    "Sale",
    "SaleItem",
    "Bill",
    "BillItem",
    "SmsMessage",
    "MSG_QUEUED",
    "MSG_SENDING",
    "MSG_SENT",
    "MSG_FAILED",
    "VALID_MESSAGE_STATUSES",
    "DEFAULT_SMS_PROVIDER",
    "Notification",
    "Alert",
    "ALERT_SHORTAGE",
    "ALERT_SURPLUS",
    "ALERT_MISPLACEMENT",
    "ALERT_EXPIRY",
    "ALERT_LOW_SHELF_OCCUPANCY",
    "ALERT_SHELF_EMPTY",
    "ALERT_CAMERA_OFFLINE",
    "ALERT_REVIEW_REQUIRED",
    "VALID_ALERT_TYPES",
    "SEV_INFO",
    "SEV_LOW",
    "SEV_MEDIUM",
    "SEV_HIGH",
    "SEV_CRITICAL",
    "VALID_SEVERITIES",
    "STATUS_OPEN",
    "STATUS_ACKNOWLEDGED",
    "STATUS_RESOLVED",
    "STATUS_DISMISSED",
    "VALID_STATUSES",
    "ALLOWED_TRANSITIONS",
    "Observation",
    "OBS_PERSON",
    "OBS_PRODUCT",
    "OBS_TEXT",
    "OBS_EXPIRY_METADATA",
    "VALID_OBSERVATION_TYPES",
    "ShelfSnapshot",
    "SNAPSHOT_EMPTY",
    "SNAPSHOT_LOW",
    "SNAPSHOT_MEDIUM",
    "SNAPSHOT_FULL",
    "VALID_SNAPSHOT_STATUSES",
    "ReconciliationResult",
    "REC_MATCH",
    "REC_SURPLUS",
    "REC_SHORTAGE",
    "REC_REVIEW",
    "VALID_RECONCILIATION_STATUSES",
    "GlobalPersonSession",
    "PersonTrackAssociation",
    "ZoneVisit",
    "PersonCameraTransition",
    "CONF_HIGH",
    "CONF_MEDIUM",
    "CONF_LOW",
    "CONF_UNKNOWN",
    "VALID_CONFIDENCES",
    "SESSION_ACTIVE",
    "SESSION_EXPIRED",
    "Insight",
    "CATEGORY_INVENTORY",
    "CATEGORY_SHELF",
    "CATEGORY_EXPIRY",
    "CATEGORY_CUSTOMER_FLOW",
    "CATEGORY_CAMERA",
    "CATEGORY_STORE_HEALTH",
    "VALID_CATEGORIES",
    "INSIGHT_LOW_STOCK",
    "INSIGHT_OUT_OF_STOCK",
    "INSIGHT_LOW_STOCK_LOW_SHELF",
    "INSIGHT_HIGH_SELLING_LOW_STOCK",
    "INSIGHT_EXPIRY_RISK",
    "INSIGHT_EXPIRED_BATCH",
    "INSIGHT_STOCK_ROTATION",
    "INSIGHT_LOW_SHELF_AVAILABILITY",
    "INSIGHT_MISPLACEMENT",
    "INSIGHT_HIGH_TRAFFIC_ZONE",
    "INSIGHT_HIGH_DWELL_ZONE",
    "INSIGHT_HIGH_TRAFFIC_LOW_SHELF",
    "INSIGHT_CAMERA_HEALTH",
    "INSIGHT_INVENTORY_RISK",
    "INSIGHT_STORE_HEALTH",
    "VALID_INSIGHT_TYPES",
    "VALID_SEVERITIES",
    "STATUS_OPEN",
    "STATUS_ACKNOWLEDGED",
    "STATUS_RESOLVED",
    "STATUS_EXPIRED",
    "VALID_STATUSES",
    "CERTAINTY_HIGH",
    "CERTAINTY_MEDIUM",
    "CERTAINTY_LOW",
    "VALID_CERTAINTIES",
]