"""m21 demo scenario state and store is_demo

Revision ID: 19c835a1a344
Revises: 3459a7512c9d
Create Date: 2026-09-17 01:46:23.578304

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '19c835a1a344'
down_revision: Union[str, Sequence[str], None] = '3459a7512c9d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('demo_scenario_state',
    sa.Column('store_id', sa.UUID(), nullable=False),
    sa.Column('active_key', sa.String(length=40), nullable=False),
    sa.Column('last_reset_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_activated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], name=op.f('fk_demo_scenario_state_store_id_stores'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_demo_scenario_state'))
    )
    op.create_index(op.f('ix_demo_scenario_state_store_id'), 'demo_scenario_state', ['store_id'], unique=True)
    op.add_column('stores', sa.Column('is_demo', sa.Boolean(), server_default='false', nullable=False))
    op.create_index(op.f('ix_stores_is_demo'), 'stores', ['is_demo'], unique=False)
    # Backfill: mark the existing seeded demo store so M21 demo tooling can
    # safely identify it by flag (not by name alone) going forward.
    op.execute(
        "UPDATE stores SET is_demo = true "
        "WHERE name = 'Storeye Demo Mart'"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stores_is_demo'), table_name='stores')
    op.drop_column('stores', 'is_demo')
    op.drop_index(op.f('ix_demo_scenario_state_store_id'), table_name='demo_scenario_state')
    op.drop_table('demo_scenario_state')
    # ### end Alembic commands ###
