"""add store intelligence insights

Revision ID: 3459a7512c9d
Revises: d96754c9650a
Create Date: 2026-09-17 00:47:54.673141

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3459a7512c9d'
down_revision: Union[str, Sequence[str], None] = 'd96754c9650a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('insights',
    sa.Column('store_id', sa.UUID(), nullable=False),
    sa.Column('category', sa.String(length=30), nullable=False),
    sa.Column('insight_type', sa.String(length=50), nullable=False),
    sa.Column('severity', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.String(length=2000), nullable=True),
    sa.Column('rule_id', sa.String(length=80), nullable=False),
    sa.Column('source_modules', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('recommended_action', sa.String(length=600), nullable=True),
    sa.Column('certainty', sa.String(length=10), nullable=False),
    sa.Column('entity_type', sa.String(length=40), nullable=False),
    sa.Column('entity_id', sa.String(length=120), nullable=False),
    sa.Column('dedupe_key', sa.String(length=180), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=True),
    sa.Column('shelf_id', sa.UUID(), nullable=True),
    sa.Column('zone_id', sa.UUID(), nullable=True),
    sa.Column('camera_id', sa.UUID(), nullable=True),
    sa.Column('first_detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expired_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['camera_id'], ['cameras.id'], name=op.f('fk_insights_camera_id_cameras'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_insights_product_id_products'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['shelf_id'], ['shelves.id'], name=op.f('fk_insights_shelf_id_shelves'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], name=op.f('fk_insights_store_id_stores'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], name=op.f('fk_insights_zone_id_zones'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_insights'))
    )
    op.create_index(op.f('ix_insights_camera_id'), 'insights', ['camera_id'], unique=False)
    op.create_index(op.f('ix_insights_category'), 'insights', ['category'], unique=False)
    op.create_index(op.f('ix_insights_first_detected_at'), 'insights', ['first_detected_at'], unique=False)
    op.create_index(op.f('ix_insights_insight_type'), 'insights', ['insight_type'], unique=False)
    op.create_index(op.f('ix_insights_last_detected_at'), 'insights', ['last_detected_at'], unique=False)
    op.create_index(op.f('ix_insights_product_id'), 'insights', ['product_id'], unique=False)
    op.create_index(op.f('ix_insights_severity'), 'insights', ['severity'], unique=False)
    op.create_index(op.f('ix_insights_shelf_id'), 'insights', ['shelf_id'], unique=False)
    op.create_index(op.f('ix_insights_status'), 'insights', ['status'], unique=False)
    op.create_index(op.f('ix_insights_store_id'), 'insights', ['store_id'], unique=False)
    op.create_index('ix_insights_store_type_key', 'insights', ['store_id', 'insight_type', 'dedupe_key'], unique=False)
    op.create_index(op.f('ix_insights_zone_id'), 'insights', ['zone_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_insights_zone_id'), table_name='insights')
    op.drop_index('ix_insights_store_type_key', table_name='insights')
    op.drop_index(op.f('ix_insights_store_id'), table_name='insights')
    op.drop_index(op.f('ix_insights_status'), table_name='insights')
    op.drop_index(op.f('ix_insights_shelf_id'), table_name='insights')
    op.drop_index(op.f('ix_insights_severity'), table_name='insights')
    op.drop_index(op.f('ix_insights_product_id'), table_name='insights')
    op.drop_index(op.f('ix_insights_last_detected_at'), table_name='insights')
    op.drop_index(op.f('ix_insights_insight_type'), table_name='insights')
    op.drop_index(op.f('ix_insights_first_detected_at'), table_name='insights')
    op.drop_index(op.f('ix_insights_category'), table_name='insights')
    op.drop_index(op.f('ix_insights_camera_id'), table_name='insights')
    op.drop_table('insights')
    # ### end Alembic commands ###
