"""add batches and batch_id on movements

Revision ID: c3a7600b329b
Revises: 4cafd848b801
Create Date: 2026-09-02 03:45:13.941589

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c3a7600b329b'
down_revision: Union[str, Sequence[str], None] = '4cafd848b801'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('batches',
    sa.Column('store_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('batch_number', sa.String(length=100), nullable=True),
    sa.Column('manufacturing_date', sa.Date(), nullable=True),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('expiry_date_precision', sa.String(length=10), nullable=False),
    sa.Column('mrp', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_batches_product_id_products'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], name=op.f('fk_batches_store_id_stores'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_batches')),
    sa.UniqueConstraint('store_id', 'product_id', 'batch_number', name='uq_batches_store_product_number')
    )
    op.create_index(op.f('ix_batches_product_id'), 'batches', ['product_id'], unique=False)
    op.create_index(op.f('ix_batches_store_id'), 'batches', ['store_id'], unique=False)
    op.add_column('inventory_movements', sa.Column('batch_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_inventory_movements_batch_id'), 'inventory_movements', ['batch_id'], unique=False)
    op.create_foreign_key(op.f('fk_inventory_movements_batch_id_batches'), 'inventory_movements', 'batches', ['batch_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_inventory_movements_batch_id_batches'), 'inventory_movements', type_='foreignkey')
    op.drop_index(op.f('ix_inventory_movements_batch_id'), table_name='inventory_movements')
    op.drop_column('inventory_movements', 'batch_id')
    op.drop_index(op.f('ix_batches_store_id'), table_name='batches')
    op.drop_index(op.f('ix_batches_product_id'), table_name='batches')
    op.drop_table('batches')
    # ### end Alembic commands ###
