"""add anonymous journeys tables

Revision ID: d96754c9650a
Revises: c4f5a6b7c8d9
Create Date: 2026-09-16 22:40:58.968046

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd96754c9650a'
down_revision: Union[str, Sequence[str], None] = 'c4f5a6b7c8d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('global_person_sessions',
    sa.Column('store_id', sa.UUID(), nullable=False),
    sa.Column('global_person_id', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('confidence', sa.String(length=20), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('camera_count', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], name=op.f('fk_global_person_sessions_store_id_stores'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_global_person_sessions')),
    sa.UniqueConstraint('store_id', 'global_person_id', name='uq_global_person_sessions_store_global')
    )
    op.create_index(op.f('ix_global_person_sessions_first_seen_at'), 'global_person_sessions', ['first_seen_at'], unique=False)
    op.create_index(op.f('ix_global_person_sessions_global_person_id'), 'global_person_sessions', ['global_person_id'], unique=False)
    op.create_index(op.f('ix_global_person_sessions_last_seen_at'), 'global_person_sessions', ['last_seen_at'], unique=False)
    op.create_index(op.f('ix_global_person_sessions_store_id'), 'global_person_sessions', ['store_id'], unique=False)
    op.create_table('person_camera_transitions',
    sa.Column('store_id', sa.UUID(), nullable=False),
    sa.Column('global_person_id', sa.String(length=64), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=True),
    sa.Column('from_camera_id', sa.UUID(), nullable=True),
    sa.Column('to_camera_id', sa.UUID(), nullable=True),
    sa.Column('transitioned_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('time_gap_seconds', sa.Float(), nullable=True),
    sa.Column('confidence', sa.String(length=20), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['from_camera_id'], ['cameras.id'], name=op.f('fk_person_camera_transitions_from_camera_id_cameras'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['session_id'], ['global_person_sessions.id'], name=op.f('fk_person_camera_transitions_session_id_global_person_sessions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], name=op.f('fk_person_camera_transitions_store_id_stores'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_camera_id'], ['cameras.id'], name=op.f('fk_person_camera_transitions_to_camera_id_cameras'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_person_camera_transitions'))
    )
    op.create_index(op.f('ix_person_camera_transitions_from_camera_id'), 'person_camera_transitions', ['from_camera_id'], unique=False)
    op.create_index(op.f('ix_person_camera_transitions_global_person_id'), 'person_camera_transitions', ['global_person_id'], unique=False)
    op.create_index(op.f('ix_person_camera_transitions_store_id'), 'person_camera_transitions', ['store_id'], unique=False)
    op.create_index(op.f('ix_person_camera_transitions_to_camera_id'), 'person_camera_transitions', ['to_camera_id'], unique=False)
    op.create_index(op.f('ix_person_camera_transitions_transitioned_at'), 'person_camera_transitions', ['transitioned_at'], unique=False)
    op.create_table('person_track_associations',
    sa.Column('store_id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('global_person_id', sa.String(length=64), nullable=False),
    sa.Column('camera_id', sa.UUID(), nullable=False),
    sa.Column('track_id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('confidence', sa.String(length=20), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['camera_id'], ['cameras.id'], name=op.f('fk_person_track_associations_camera_id_cameras'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['session_id'], ['global_person_sessions.id'], name=op.f('fk_person_track_associations_session_id_global_person_sessions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], name=op.f('fk_person_track_associations_store_id_stores'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_person_track_associations')),
    sa.UniqueConstraint('session_id', 'camera_id', 'track_id', name='uq_person_track_associations_session_camera_track')
    )
    op.create_index(op.f('ix_person_track_associations_camera_id'), 'person_track_associations', ['camera_id'], unique=False)
    op.create_index('ix_person_track_associations_camera_track', 'person_track_associations', ['camera_id', 'track_id'], unique=False)
    op.create_index(op.f('ix_person_track_associations_global_person_id'), 'person_track_associations', ['global_person_id'], unique=False)
    op.create_index(op.f('ix_person_track_associations_store_id'), 'person_track_associations', ['store_id'], unique=False)
    op.create_table('zone_visits',
    sa.Column('store_id', sa.UUID(), nullable=False),
    sa.Column('global_person_id', sa.String(length=64), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=True),
    sa.Column('zone_id', sa.UUID(), nullable=False),
    sa.Column('camera_id', sa.UUID(), nullable=True),
    sa.Column('entered_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('exited_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('dwell_seconds', sa.Float(), nullable=True),
    sa.Column('confidence', sa.String(length=20), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['camera_id'], ['cameras.id'], name=op.f('fk_zone_visits_camera_id_cameras'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['session_id'], ['global_person_sessions.id'], name=op.f('fk_zone_visits_session_id_global_person_sessions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], name=op.f('fk_zone_visits_store_id_stores'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], name=op.f('fk_zone_visits_zone_id_zones'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_zone_visits'))
    )
    op.create_index(op.f('ix_zone_visits_camera_id'), 'zone_visits', ['camera_id'], unique=False)
    op.create_index(op.f('ix_zone_visits_entered_at'), 'zone_visits', ['entered_at'], unique=False)
    op.create_index(op.f('ix_zone_visits_global_person_id'), 'zone_visits', ['global_person_id'], unique=False)
    op.create_index(op.f('ix_zone_visits_store_id'), 'zone_visits', ['store_id'], unique=False)
    op.create_index(op.f('ix_zone_visits_zone_id'), 'zone_visits', ['zone_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_zone_visits_zone_id'), table_name='zone_visits')
    op.drop_index(op.f('ix_zone_visits_store_id'), table_name='zone_visits')
    op.drop_index(op.f('ix_zone_visits_global_person_id'), table_name='zone_visits')
    op.drop_index(op.f('ix_zone_visits_entered_at'), table_name='zone_visits')
    op.drop_index(op.f('ix_zone_visits_camera_id'), table_name='zone_visits')
    op.drop_table('zone_visits')
    op.drop_index(op.f('ix_person_track_associations_store_id'), table_name='person_track_associations')
    op.drop_index(op.f('ix_person_track_associations_global_person_id'), table_name='person_track_associations')
    op.drop_index('ix_person_track_associations_camera_track', table_name='person_track_associations')
    op.drop_index(op.f('ix_person_track_associations_camera_id'), table_name='person_track_associations')
    op.drop_table('person_track_associations')
    op.drop_index(op.f('ix_person_camera_transitions_transitioned_at'), table_name='person_camera_transitions')
    op.drop_index(op.f('ix_person_camera_transitions_to_camera_id'), table_name='person_camera_transitions')
    op.drop_index(op.f('ix_person_camera_transitions_store_id'), table_name='person_camera_transitions')
    op.drop_index(op.f('ix_person_camera_transitions_global_person_id'), table_name='person_camera_transitions')
    op.drop_index(op.f('ix_person_camera_transitions_from_camera_id'), table_name='person_camera_transitions')
    op.drop_table('person_camera_transitions')
    op.drop_index(op.f('ix_global_person_sessions_store_id'), table_name='global_person_sessions')
    op.drop_index(op.f('ix_global_person_sessions_last_seen_at'), table_name='global_person_sessions')
    op.drop_index(op.f('ix_global_person_sessions_global_person_id'), table_name='global_person_sessions')
    op.drop_index(op.f('ix_global_person_sessions_first_seen_at'), table_name='global_person_sessions')
    op.drop_table('global_person_sessions')
    # ### end Alembic commands ###
