"""add ai observations

Revision ID: e31098126b9c
Revises: c3a7600b329b
Create Date: 2026-09-02 03:57:35.948116

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e31098126b9c'
down_revision: Union[str, Sequence[str], None] = 'c3a7600b329b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('observations',
    sa.Column('observation_type', sa.String(length=40), nullable=False),
    sa.Column('store_id', sa.UUID(), nullable=True),
    sa.Column('camera_id', sa.UUID(), nullable=True),
    sa.Column('product_id', sa.UUID(), nullable=True),
    sa.Column('batch_id', sa.UUID(), nullable=True),
    sa.Column('track_id', sa.Integer(), nullable=True),
    sa.Column('frame_number', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(length=500), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('bbox', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('source_observation_id', sa.UUID(), nullable=True),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['batches.id'], name=op.f('fk_observations_batch_id_batches'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['camera_id'], ['cameras.id'], name=op.f('fk_observations_camera_id_cameras'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_observations_product_id_products'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_observation_id'], ['observations.id'], name=op.f('fk_observations_source_observation_id_observations'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], name=op.f('fk_observations_store_id_stores'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_observations'))
    )
    op.create_index(op.f('ix_observations_batch_id'), 'observations', ['batch_id'], unique=False)
    op.create_index(op.f('ix_observations_camera_id'), 'observations', ['camera_id'], unique=False)
    op.create_index(op.f('ix_observations_observation_type'), 'observations', ['observation_type'], unique=False)
    op.create_index(op.f('ix_observations_observed_at'), 'observations', ['observed_at'], unique=False)
    op.create_index(op.f('ix_observations_product_id'), 'observations', ['product_id'], unique=False)
    op.create_index(op.f('ix_observations_source_observation_id'), 'observations', ['source_observation_id'], unique=False)
    op.create_index(op.f('ix_observations_store_id'), 'observations', ['store_id'], unique=False)
    op.create_index(op.f('ix_observations_track_id'), 'observations', ['track_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_observations_track_id'), table_name='observations')
    op.drop_index(op.f('ix_observations_store_id'), table_name='observations')
    op.drop_index(op.f('ix_observations_source_observation_id'), table_name='observations')
    op.drop_index(op.f('ix_observations_product_id'), table_name='observations')
    op.drop_index(op.f('ix_observations_observed_at'), table_name='observations')
    op.drop_index(op.f('ix_observations_observation_type'), table_name='observations')
    op.drop_index(op.f('ix_observations_camera_id'), table_name='observations')
    op.drop_index(op.f('ix_observations_batch_id'), table_name='observations')
    op.drop_table('observations')
    # ### end Alembic commands ###
