"""Pydantic request/response schemas for the Storeye FastAPI API.

These define the API contract. Database/ORM models are NEVER exposed
directly; the API layer maps to/from these schemas.
"""

from .store import StoreCreate, StoreRead, StoreUpdate, StoreList
from .demo import (
    DemoActivationResult,
    DemoScenarioList,
    DemoScenarioRead,
    DemoStatusRead,
)
from .user import UserCreate, UserRead, UserUpdate, UserList
from .auth import AuthUserRead, ChangePasswordIn, LoginIn, LoginResponse, MessageOut
from .camera import CameraCreate, CameraRead, CameraUpdate, CameraList
from .zone import ZoneAnalyticsRead, ZoneCreate, ZoneRead, ZoneUpdate, ZoneList
from .shelf import ShelfCreate, ShelfRead, ShelfUpdate, ShelfList
from .shelf_snapshot import (
    ShelfHistoryRead,
    ShelfSnapshotListRead,
    ShelfSnapshotRead,
    ShelfSnapshotSummaryRead,
    ShelfStatusCounts,
)
from .product import ProductCreate, ProductRead, ProductUpdate, ProductList
from .batch import BatchCreate, BatchRead, BatchUpdate, BatchList
from .inventory import (
    AdjustStockIn,
    InventoryMovementList,
    InventoryMovementRead,
    InventoryRead,
    InventorySetReorder,
    InventorySummaryRead,
    ReceiveStockIn,
    RecordMovementIn,
)
from .customer import CustomerCreate, CustomerRead, CustomerUpdate, CustomerList
from .sale import SaleCreate, SaleItemCreate, SaleItemRead, SaleList, SaleRead
from .bill import (
    BillCreate,
    BillItemCreate,
    BillItemRead,
    BillList,
    BillRead,
    BillUpdate,
)
from .sms import (
    SmsMessageList,
    SmsMessageRead,
    SmsStatusCounts,
    SmsStatusRead,
)
from .notification import (
    NotificationCreate,
    NotificationList,
    NotificationRead,
    NotificationUpdate,
)
from .alert import (
    AlertCreate,
    AlertEvaluateIn,
    AlertEvaluateResult,
    AlertList,
    AlertRead,
    AlertUpdate,
)
from .observation import (
    ActivityBucket,
    ObservationCreate,
    ObservationList,
    ObservationRead,
    ObservationSummary,
)
from .reconciliation import (
    ReconciliationResultList,
    ReconciliationResultRead,
    ReconciliationRunIn,
)
from .batch_intake import (
    BatchConfirmIn,
    BatchReceiptRead,
    BatchScanCandidateRead,
    BatchScanRead,
)
from .intelligence import (
    AISummaryRead,
    CameraSummaryRead,
    MisplacementList,
    MisplacementRead,
    PeopleSummaryRead,
    ProductCandidateList,
    ProductCandidateRead,
    ProductIntelligenceList,
    ProductIntelligenceRead,
    ProductSummaryRead,
    ReconciliationSummaryRead,
    ShelfIntelligenceList,
    ShelfIntelligenceRead,
    ShelfSummaryRead,
    ShelfVisibleProductRead,
)
from .journey import (
    CameraVisitedRead,
    DailyFootfallListRead,
    DailyFootfallRead,
    JourneyDetailRead,
    JourneyItemRead,
    JourneyListRead,
    JourneySummaryRead,
    MostVisitedZoneRead,
    TimelineEventRead,
    TrackAssociationRead,
    TransitionRead,
    ZoneVisitedRead,
    ZoneVisitRead,
)
from .insight import (
    InsightEvaluateIn,
    InsightEvaluateResult,
    InsightFilterIn,
    InsightList,
    InsightRead,
    InsightStatusIn,
    InsightSummary,
    StoreHealthMetrics,
)

__all__ = [
    "StoreCreate",
    "StoreRead",
    "StoreUpdate",
    "StoreList",
    "UserCreate",
    "UserRead",
    "UserUpdate",
    "UserList",
    "AuthUserRead",
    "ChangePasswordIn",
    "LoginIn",
    "LoginResponse",
    "MessageOut",
    "CameraCreate",
    "CameraRead",
    "CameraUpdate",
    "CameraList",
    "ZoneCreate",
    "ZoneRead",
    "ZoneUpdate",
    "ZoneList",
    "ZoneAnalyticsRead",
    "ShelfCreate",
    "ShelfRead",
    "ShelfUpdate",
    "ShelfList",
    "ShelfHistoryRead",
    "ShelfSnapshotListRead",
    "ShelfSnapshotRead",
    "ShelfSnapshotSummaryRead",
    "ShelfStatusCounts",
    "ProductCreate",
    "ProductRead",
    "ProductUpdate",
    "ProductList",
    "BatchCreate",
    "BatchRead",
    "BatchUpdate",
    "BatchList",
    "AdjustStockIn",
    "InventoryMovementList",
    "InventoryMovementRead",
    "InventoryRead",
    "InventorySetReorder",
    "InventorySummaryRead",
    "ReceiveStockIn",
    "RecordMovementIn",
    "CustomerCreate",
    "CustomerRead",
    "CustomerUpdate",
    "CustomerList",
    "SaleCreate",
    "SaleItemCreate",
    "SaleItemRead",
    "SaleList",
    "SaleRead",
    "BillCreate",
    "BillItemCreate",
    "BillItemRead",
    "BillList",
    "BillRead",
    "BillUpdate",
    "SmsMessageList",
    "SmsMessageRead",
    "SmsStatusCounts",
    "SmsStatusRead",
    "NotificationCreate",
    "NotificationList",
    "NotificationRead",
    "NotificationUpdate",
    "AlertCreate",
    "AlertEvaluateIn",
    "AlertEvaluateResult",
    "AlertList",
    "AlertRead",
    "AlertUpdate",
    "ObservationCreate",
    "ObservationList",
    "ObservationRead",
    "ObservationSummary",
    "ActivityBucket",
    "ReconciliationResultList",
    "ReconciliationResultRead",
    "ReconciliationRunIn",
    "BatchConfirmIn",
    "BatchReceiptRead",
    "BatchScanCandidateRead",
    "BatchScanRead",
    "AISummaryRead",
    "CameraSummaryRead",
    "MisplacementList",
    "MisplacementRead",
    "PeopleSummaryRead",
    "ProductSummaryRead",
    "ProductCandidateList",
    "ProductCandidateRead",
    "ProductIntelligenceList",
    "ProductIntelligenceRead",
    "ReconciliationSummaryRead",
    "ShelfIntelligenceList",
    "ShelfIntelligenceRead",
    "ShelfSummaryRead",
    "ShelfVisibleProductRead",
    "CameraVisitedRead",
    "DailyFootfallListRead",
    "DailyFootfallRead",
    "JourneyDetailRead",
    "JourneyItemRead",
    "JourneyListRead",
    "JourneySummaryRead",
    "MostVisitedZoneRead",
    "TimelineEventRead",
    "TrackAssociationRead",
    "TransitionRead",
    "ZoneVisitedRead",
    "ZoneVisitRead",
    "InsightEvaluateIn",
    "InsightEvaluateResult",
    "InsightFilterIn",
    "InsightList",
    "InsightRead",
    "InsightStatusIn",
    "InsightSummary",
    "StoreHealthMetrics",
    "DemoScenarioRead",
    "DemoScenarioList",
    "DemoStatusRead",
    "DemoActivationResult",
]
